FROM debian:11

RUN apt update 
RUN apt upgrade

RUN apt -y install python3
RUN apt -y install python3-pip 
RUN apt -y install python3-venv
RUN pip install virtualenv

WORKDIR /root

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN rm requirements.txt
RUN echo "alias ipython='python3 -m IPython'" >> .bashrc
